package com.highlighthub.game;

import java.util.List;
import java.util.Map;

/**
 * Genre taxonomy from the market survey (docs/game-genres.md).
 * Static, versioned in code: genre presets only guide ROI calibration and
 * rule defaults - they never claim recognition capability for any game.
 */
public final class GenreCatalog {
    private GenreCatalog() {}

    public record Genre(String key, String name, String description,
                        List<String> typicalEvents, List<String> exampleGames,
                        Map<String, Double> suggestedRoi) {}

    public static final List<Genre> ALL = List.of(
            new Genre("moba", "MOBA / 多人在线战术竞技",
                    "击杀播报横幅驱动；关注团战窗口",
                    List.of("ELIMINATION_NOTICE", "ROUND_END"),
                    List.of("英雄联盟", "Dota2", "王者荣耀"),
                    Map.of("announcementX", 0.30, "announcementY", 0.05, "announcementW", 0.40, "announcementH", 0.10)),
            new Genre("fps", "第一人称射击",
                    "右上角击杀信息流(Killfeed)驱动",
                    List.of("ELIMINATION_NOTICE", "SCORE_CHANGE"),
                    List.of("CS2", "无畏契约", "使命召唤"),
                    Map.of("killfeedX", 0.60, "killfeedY", 0.02, "killfeedW", 0.38, "killfeedH", 0.25)),
            new Genre("tps", "第三人称射击",
                    "击杀信息流 + 淘汰播报",
                    List.of("ELIMINATION_NOTICE"),
                    List.of("PUBG", "战争前线"),
                    Map.of("killfeedX", 0.60, "killfeedY", 0.02, "killfeedW", 0.38, "killfeedH", 0.25)),
            new Genre("battle-royale", "大逃杀",
                    "击倒数与剩余存活数变化",
                    List.of("ELIMINATION_NOTICE", "SCORE_CHANGE"),
                    List.of("Apex英雄", "堡垒之夜", "和平精英"),
                    Map.of("killfeedX", 0.60, "killfeedY", 0.02, "killfeedW", 0.38, "killfeedH", 0.25)),
            new Genre("rts", "即时战略",
                    "大规模团战节点 + 胜负画面",
                    List.of("ROUND_END", "MANUAL_MARKER"),
                    List.of("星际争霸2", "魔兽争霸3"),
                    Map.of("resourceX", 0.0, "resourceY", 0.0, "resourceW", 0.2, "resourceH", 0.08)),
            new Genre("racing", "竞速",
                    "名次变化与圈数计时",
                    List.of("SCORE_CHANGE"),
                    List.of("极品飞车", "马里奥赛车8", "F1"),
                    Map.of("positionX", 0.0, "positionY", 0.05, "positionW", 0.15, "positionH", 0.12)),
            new Genre("sports", "体育竞技",
                    "比分牌变化 + 得分回放横幅",
                    List.of("SCORE_CHANGE"),
                    List.of("EA FC", "NBA 2K", "火箭联盟"),
                    Map.of("scoreboardX", 0.35, "scoreboardY", 0.0, "scoreboardW", 0.3, "scoreboardH", 0.08)),
            new Genre("fighting", "格斗",
                    "回合胜利标记 + 连段",
                    List.of("ROUND_END", "MANUAL_MARKER"),
                    List.of("街霸6", "铁拳8"),
                    Map.of("roundPipX", 0.0, "roundPipY", 0.0, "roundPipW", 0.2, "roundPipH", 0.06)),
            new Genre("card-battler", "卡牌/自走棋",
                    "伤害数字与回合边界",
                    List.of("SCORE_CHANGE", "ROUND_START"),
                    List.of("炉石传说", "云顶之弈"),
                    Map.of("boardX", 0.2, "boardY", 0.3, "boardW", 0.6, "boardH", 0.3)),
            new Genre("mmo", "MMORPG",
                    "团本提示与 PVP 击杀信息流",
                    List.of("ELIMINATION_NOTICE", "MANUAL_MARKER"),
                    List.of("魔兽世界", "最终幻想14", "剑网3"),
                    Map.of("killfeedX", 0.6, "killfeedY", 0.02, "killfeedW", 0.38, "killfeedH", 0.25)),
            new Genre("sandbox-survival", "沙盒/生存建造",
                    "PVP 击杀与 Boss 战，多用手动标记",
                    List.of("MANUAL_MARKER", "ELIMINATION_NOTICE"),
                    List.of("我的世界", "Rust", "方舟"),
                    Map.of("killfeedX", 0.6, "killfeedY", 0.02, "killfeedW", 0.38, "killfeedH", 0.25)),
            new Genre("action-soulslike", "动作/魂类",
                    "Boss 战与处决节点",
                    List.of("MANUAL_MARKER"),
                    List.of("艾尔登法环", "只狼", "黑神话:悟空"),
                    Map.of("bossBarX", 0.2, "bossBarY", 0.85, "bossBarW", 0.6, "bossBarH", 0.08)),
            new Genre("roguelike", "Roguelike/Roguelite",
                    "关卡推进与 Boss 击杀",
                    List.of("ROUND_END", "MANUAL_MARKER"),
                    List.of("哈迪斯", "杀戮尖塔"),
                    Map.of("stageX", 0.4, "stageY", 0.0, "stageW", 0.2, "stageH", 0.06)),
            new Genre("openworld-arpg", "开放世界 ARPG",
                    "Boss 挑战与秘境计时",
                    List.of("MANUAL_MARKER", "SCORE_CHANGE"),
                    List.of("原神", "塞尔达传说", "黑神话:悟空"),
                    Map.of("timerX", 0.4, "timerY", 0.0, "timerW", 0.2, "timerH", 0.06)),
            new Genre("simulation", "模拟/经营",
                    "高光密度低，以展示集锦为主",
                    List.of("MANUAL_MARKER"),
                    List.of("模拟人生", "星露谷物语", "城市:天际线"),
                    Map.of()),
            new Genre("rhythm", "音乐节奏",
                    "COMBO 与全连提示",
                    List.of("SCORE_CHANGE"),
                    List.of("OSU!", "Phigros"),
                    Map.of("comboX", 0.4, "comboY", 0.2, "comboW", 0.2, "comboH", 0.15)),
            new Genre("horror-puzzle", "恐怖/解谜",
                    "依赖手动标记",
                    List.of("MANUAL_MARKER"),
                    List.of("生化危机", "双人成行"),
                    Map.of()),
            new Genre("platformer", "平台跳跃",
                    "死亡计数与速通计时",
                    List.of("MANUAL_MARKER", "SCORE_CHANGE"),
                    List.of("马里奥", "空洞骑士", "蔚蓝"),
                    Map.of("timerX", 0.4, "timerY", 0.0, "timerW", 0.2, "timerH", 0.06)),
            new Genre("strategy-tbs", "回合制策略",
                    "战斗结算画面",
                    List.of("ROUND_END"),
                    List.of("文明6", "全面战争"),
                    Map.of()),
            new Genre("party-casual", "派对/休闲对抗",
                    "晋级/淘汰横幅",
                    List.of("ROUND_END"),
                    List.of("糖豆人", "蛋仔派对", "Among Us"),
                    Map.of("bannerX", 0.2, "bannerY", 0.3, "bannerW", 0.6, "bannerH", 0.2)),
            new Genre("other", "其他/未分类",
                    "建议全程手动标记 + 手动剪辑",
                    List.of("MANUAL_MARKER"),
                    List.of(),
                    Map.of()));

    public static boolean exists(String key) {
        return ALL.stream().anyMatch(g -> g.key().equals(key));
    }
}
